services:
  - type: web
    name: studytool-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm ci"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: OPENAI_MAX_TOKENS
        sync: false
      - key: OPENAI_RPM
        sync: false
      - key: OPENAI_CONCURRENCY
        sync: false
      - key: SERVER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
